name: deno

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stable:
    name: Deno ${{ matrix.deno }} in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        deno: ["v0.20.0", "v0.38.0", "v0.x", "v1.x", "nightly"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        working-directory: ./MoviesWebClient/MoviesWebClient/ClientApp/

      - name: Check
        run: npm run check
        working-directory: ./MoviesWebClient/MoviesWebClient/ClientApp/

      - name: Build
        run: npm run build
        working-directory: ./MoviesWebClient/MoviesWebClient/ClientApp/

      - name: Set up Deno ${{ matrix.deno }}
        uses: ./
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run deno
        run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts
        working-directory: ./MoviesWebClient/MoviesWebClient/ClientApp/
        
      - name: Run deno installed cli
        if: matrix.deno == 'v1.x' || matrix.deno == 'nightly'
        run: |
          deno install --allow-read -n deno_cat https://deno.land/std/examples/cat.ts
          deno_cat ./README.md
        working-directory: ./MoviesWebClient/MoviesWebClient/ClientApp/
